#Login
LOGIN_BUTTON = '//a[contains(@class, "login")]'
USERNAME_FIELD = '//*[@id="username"]'
PASSWORD_FIELD = '//*[@id="password"]'
LOGIN_BUTTON2 =  '//input[@value= "Login"]'
LOG_OUT_ELEMENT = '//a[contains(text(), "Log out")]'
#Createnewpoll
ADD_NEW_PROJECT = '(//a[contains(@class, "add-project")])[1]'
ADD_PROJECT_NAME = '//*[@id="addProjectName"]'
#QWL
CREATE_QWL_POLL_BUTTON = 'text="Create a QWL poll"'
QWL_TYPE_OPTIONS = '//select[option[@value="complete"]]'
ORGANIZATION_TYPE_OPTIONS = '//select[option[contains(text(),"traditional")]]'
HIDE_VECTOR_GRAPHS_CHECKBOX = '//input[@type="checkbox"]'
#Custompoll
CREATE_CUSTOM_POLL_BUTTON = 'text="Create a custom poll"'
ADD_QUESTIONS_BUTTON = '//a[contains(text(),"Add questions")]'
TYPE_QUESTIONS_FIELD = '//*[@id="customQuestionText"]'
ADD_QUESTIONS_BUTTON2 = '//button[contains(text(),"Add questions")]'
#removepolls
PROJECT_ROW = '//div[@id="masterContainer"]//div[contains(@class, "projectRow")]'
CHANGE_POLL_SETTINGS = '(//a[@mattooltip="Change poll\'s settings"])[1]'
DELETE_POLL_BUTTON = '//vibe-settings-advanced-button[@icon="trash"]'
DELETE_PROJECT_BUTTON = '//a[contains(@class, "delete-project")]'
DELETE_NOW_POLL_BUTTON = '//button[contains(text(), "Delete now")]'
TYPE_DESTROY_FIELD = '//input[@vibeselecttext]'
VERIFY_REMOVAL_OK_BUTTON = '//button[contains(@class, "promptOkButton")]'
PROJECT_ROW = '//div[@id="masterContainer"]//div[contains(@class, "projectRow")]'
#answerpoll #answerlocators
QUANTATIVE_0 = '//form-root/div/div[not(@hidden)]//a[@title="Quantity needs to be increased dramatically"]'
QUANTATIVE_1 = '//form-root/div/div[not(@hidden)]//a[@title="Quantity needs to be increased considerably"]'         
QUANTATIVE_2 = '//form-root/div/div[not(@hidden)]//a[@title="Quantity needs to be increased somewhat"]'
QUANTATIVE_3 = '//form-root/div/div[not(@hidden)]//a[@title="Quantity needs to be increased slightly"]'
ALL_GOOD_4 = '//form-root/div/div[not(@hidden)]//a[@title="Quantity and quality are good"]'
QUALITY_3 = '//form-root/div/div[not(@hidden)]//a[@title="Quality needs to be improved slightly"]'
QUALITY_2 = '//form-root/div/div[not(@hidden)]//a[@title="Quality needs to be improved somewhat"]'
QUALITY_1 = '//form-root/div/div[not(@hidden)]//a[@title="Quality needs to be improved considerably"]'
QUALITY_0 = '//form-root/div/div[not(@hidden)]//a[@title="Quality needs to be improved dramatically"]'
NEXT_BUTTON_FEEDBACK = '//a[@class="nextButton"]'
NEXT_PAGE_BUTTON_QWL_POLL = '//a[contains(@class,"nextPage")]'
SEND_FEEDBACK_BUTTON = '//span[@class="pageButton sendFeedbackPageButton nextPage"]'
THANK_YOU_FEEDBACK_MESSAGE = '//div[normalize-space(text())="Thank you for your feedback!"]'
#create360poll
CREATE_360_POLL_BUTTON = '//button[normalize-space()="Create a 360 feedback poll"]'
ADD_QUESTION_BUTTON = '//vibe-settings-resources//a[contains(text(), "Add")]'
SELECT_NEW_QUESTION = '//select[@id="readyMade"]'
CLICK_FIRST_CHOICE = '(//a[@class="mat-mdc-tooltip-trigger btn btn-minimal"][normalize-space()="Select"])[1]'
ADD_SELECTED_QUESTION = '//button[normalize-space()="Add 1 selected question"]'
#answer360poll
ENTER_NAME_POLL_ANSWER = '//input[@placeholder="Enter your name here"]'
ENTER_EMAIL_POLL_ANSWER = '//input[@placeholder="Enter your email here"]'
CONTAINS_EVALUATION_REPORT = '//*[contains(text(), "evaluation report")]'
#answercustompoll
WORST_ICON = '//div[contains(@class,"question") and contains(@class, "fullHeight") and not(@hidden)]//a[1]//img'
POOR_ICON = '//div[contains(@class,"question") and contains(@class, "fullHeight") and not(@hidden)]//a[2]//img'
AVERAGE_ICON = '//div[contains(@class,"question") and contains(@class, "fullHeight") and not(@hidden)]//a[3]//img'
GOOD_ICON = '//div[contains(@class,"question") and contains(@class, "fullHeight") and not(@hidden)]//a[4]//img'
BEST_ICON = '//div[contains(@class,"question") and contains(@class, "fullHeight") and not(@hidden)]//a[5]//img'
